#!/bin/bash

FRAMEWORK_PATH="/projects/hira/15190-14030/Daniele/NW_Calibrations/"

cat > submit.sh << EOF
#!/usr/bin/env bash
#--- sbatch option ---#
#SBATCH --time=100:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=5000
#SBATCH --job-name=$2
#SBATCH --output=slurm/$1_$2.out


module add intel

cd ${FRAMEWORK_PATH}
eval './$1 $2 $3 $4'
EOF

sbatch submit.sh

rm submit.sh
